Repository keep-starknet-strange/madara, pull requests merged in 2023-06, with the labels that each got.

#323 feat: RPC - `getTransactionByHash` - `getTransactionReceipt`
  .gitignore
  crates/client/db/src/lib.rs
  crates/client/db/src/mapping_db.rs
  crates/client/mapping-sync/src/sync_blocks.rs
  crates/client/rpc-core/src/lib.rs
  crates/client/rpc/src/lib.rs
  crates/pallets/starknet/src/lib.rs
  crates/primitives/starknet/src/block/mod.rs
  crates/primitives/starknet/src/transaction/types.rs
  crates/runtime/src/lib.rs
  examples/rpc/starknet/starknet_getTransactionByHash.hurl
  examples/rpc/starknet/starknet_getTransactionReceipt.hurl
  tests/tests/test-rpc/test-starknet-rpc.ts
  tests/util/setup-dev-tests.ts
Labels: rpc, feature

#483 feat: Improve docker-compose performance
  infra/docker/docker-compose.yml
Labels: feature, devops

#526 fix: program deserialising
  crates/primitives/starknet/src/execution/contract_class_wrapper.rs
  crates/primitives/starknet/src/execution/program_wrapper.rs
Labels: testing, Fix

#514 feat: move calculation of deployed account address #500
  crates/client/rpc-core/src/utils.rs
  crates/client/rpc/src/lib.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/tests/deploy_account_tx.rs
  crates/pallets/starknet/src/tests/mock.rs
  crates/primitives/starknet/Cargo.toml
  crates/primitives/starknet/src/crypto/commitment/mod.rs
  crates/primitives/starknet/src/tests/crypto.rs
  crates/primitives/starknet/src/transaction/types.rs
  crates/runtime/src/lib.rs
Labels: enhancement, feature

#547 fix: remove block information from tx receipt fields
  crates/client/rpc/src/lib.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/tests/invoke_tx.rs
  crates/primitives/starknet/src/transaction/mod.rs
  crates/primitives/starknet/src/transaction/types.rs
  tests/tests/test-rpc/test-starknet-rpc.ts
  tests/tests/test-rpc/types.ts
Labels: testing, refacto

#485 fix: to_rpc_contract_class ✨
  Cargo.lock
  crates/client/rpc-core/src/utils.rs
  crates/client/rpc/src/lib.rs
  crates/primitives/starknet/src/execution/entrypoint_wrapper.rs
  tests/contracts/compiled/test.json
  tests/tests/test-rpc/test-starknet-rpc.ts
Labels: rpc, Fix

#566 fix: serialize field element to hex
  Cargo.lock
  Cargo.toml
  crates/client/rpc-core/Cargo.toml
  crates/client/rpc-core/src/lib.rs
  crates/client/rpc/src/lib.rs
  tests/tests/test-rpc/test-starknet-rpc.ts
Labels: Fix

#583 feat: optimize chain id retrieval
  crates/client/rpc-core/src/lib.rs
  crates/client/rpc/src/lib.rs
  crates/client/storage/src/overrides/mod.rs
  crates/client/storage/src/overrides/schema_v1_override.rs
  crates/primitives/starknet/src/execution/felt252_wrapper.rs
  crates/primitives/starknet/src/storage/mod.rs
Labels: enhancement, refacto

#590 fix from utf8 function for felt252
  crates/primitives/starknet/src/execution/felt252_wrapper.rs
  tests/tests/test-rpc/test-starknet-rpc.ts
Labels: bug, testing

#594 🔥 remove `pallet_utility`
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/lib.rs
  crates/runtime/src/pallets.rs
Labels: enhancement, devx:build-time

#604 ✨ internalize block proposer logic
  Cargo.lock
  Cargo.toml
  benchmarking/scripts/starknet-erc20.yml
  crates/client/block-proposer/Cargo.toml
  crates/client/block-proposer/src/lib.rs
  crates/client/db/Cargo.toml
  crates/client/mapping-sync/Cargo.toml
  crates/client/rpc-core/Cargo.toml
  crates/client/rpc/Cargo.toml
  crates/client/storage/Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/service.rs
  crates/pallets/starknet/Cargo.toml
  crates/primitives/starknet/Cargo.toml
  crates/runtime/Cargo.toml
Labels: enhancement, performance

#538 fix(validate): add dependency to previous tx
  crates/pallets/starknet/src/lib.rs
  scripts/run_node.sh
Labels: Fix

#601 Refacto contract serialization
  Cargo.lock
  crates/client/rpc-core/src/utils.rs
  crates/node/src/command.rs
  crates/primitives/starknet/src/block/mod.rs
  crates/primitives/starknet/src/execution/contract_class_wrapper.rs
  crates/primitives/starknet/src/execution/entrypoint_wrapper.rs
  crates/primitives/starknet/src/execution/mod.rs
  crates/primitives/starknet/src/execution/program_wrapper.rs
  crates/primitives/starknet/src/tests/execution.rs
  crates/primitives/starknet/src/transaction/types.rs
Labels: enhancement, performance, refacto

#580 Get events unit tests
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/client/rpc/Cargo.toml
  crates/client/rpc/src/events/mod.rs
  crates/client/rpc/src/events/tests.rs
  crates/client/rpc/src/lib.rs
  crates/pallets/starknet/Cargo.toml
  crates/primitives/starknet/Cargo.toml
Labels: enhancement, testing, rpc

#554 GKE Kustomize / ConfigConnector manifests
  infra/kustomize/gke/deployment.yaml
  infra/kustomize/gke/kustomization.yaml
  infra/kustomize/gke/network.yaml
  infra/kustomize/gke/service.yaml
Labels: enhancement, devops

#597 broadcast transaction conversions refactor
  Cargo.lock
  crates/client/rpc-core/src/utils.rs
  crates/client/rpc/src/lib.rs
  crates/primitives/starknet/Cargo.toml
  crates/primitives/starknet/src/transaction/mod.rs
  crates/primitives/starknet/src/transaction/types.rs
  crates/primitives/starknet/src/transaction/utils.rs
Labels: enhancement, refacto

#622 fix: add pool futures to pending transactions
  Cargo.lock
  crates/client/rpc/Cargo.toml
  crates/client/rpc/src/events/mod.rs
  crates/client/rpc/src/lib.rs
  crates/node/src/rpc/mod.rs
  crates/node/src/service.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/tests/declare_tx.rs
  crates/pallets/starknet/src/tests/invoke_tx.rs
  crates/pallets/starknet/src/tests/l1_message.rs
  tests/tests/test-rpc/test-starknet-rpc.ts
Labels: Fix

#668 feat: nonce type 🔨
  crates/pallets/starknet/src/blockifier_state_adapter.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/types.rs
Labels: Fix

#595 feat: remove CurrentBlock storage from starknet pallet
  crates/client/mapping-sync/src/sync_blocks.rs
  crates/client/rpc/src/lib.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/runtime_api.rs
  crates/pallets/starknet/src/tests/current_block.rs
  crates/pallets/starknet/src/tests/mod.rs
  crates/primitives/starknet/src/execution/call_entrypoint_wrapper.rs
  crates/primitives/starknet/src/tests/execution.rs
  crates/runtime/src/lib.rs
  docs/rpc-contribution.md
Labels: enhancement, refacto

#706 fix: rebasing deps
  Cargo.lock
  Cargo.toml
  crates/node/src/chain_spec.rs
  crates/pallets/starknet/Cargo.toml
  crates/pallets/starknet/src/blockifier_state_adapter.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/message.rs
  crates/pallets/starknet/src/tests/deploy_account_tx.rs
  crates/pallets/starknet/src/tests/erc20.rs
  crates/pallets/starknet/src/tests/invoke_tx.rs
  crates/pallets/starknet/src/tests/utils.rs
  crates/primitives/starknet/src/constants.rs
  crates/primitives/starknet/src/execution/call_entrypoint_wrapper.rs
  crates/primitives/starknet/src/execution/contract_class_wrapper.rs
  crates/primitives/starknet/src/fees/mod.rs
  crates/primitives/starknet/src/lib.rs
  crates/primitives/starknet/src/starknet_serde/mod.rs
  crates/primitives/starknet/src/state/mod.rs
  crates/primitives/starknet/src/tests/execution.rs
  crates/primitives/starknet/src/tests/starknet_serde.rs
  crates/primitives/starknet/src/tests/state.rs
  crates/primitives/starknet/src/tests/utils.rs
  crates/primitives/starknet/src/transaction/mod.rs
  crates/primitives/starknet/src/transaction/types.rs
  resources/transactions/invoke.json
  resources/transactions/invoke_argent.json
  resources/transactions/invoke_braavos.json
  resources/transactions/invoke_emit_event.json
  resources/transactions/invoke_erc20_transfer.json
  resources/transactions/invoke_invalid_version.json
  resources/transactions/invoke_nonce.json
  resources/transactions/invoke_openzeppelin.json
  resources/transactions/storage_read_write.json
  tests/tests/test-rpc/test-starknet-rpc.ts
Labels: testing, dependencies, refacto

#713 fix: link FIXMEs with issues
  crates/client/rpc-core/src/utils.rs
  crates/node/src/chain_spec.rs
  crates/pallets/starknet/src/blockifier_state_adapter.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/message.rs
  crates/pallets/starknet/src/tests/utils.rs
  crates/primitives/starknet/src/execution/contract_class_wrapper.rs
  crates/primitives/starknet/src/starknet_serde/mod.rs
  crates/primitives/starknet/src/state/mod.rs
  crates/primitives/starknet/src/tests/utils.rs
  crates/primitives/starknet/src/transaction/mod.rs
  crates/primitives/starknet/src/transaction/types.rs
  crates/runtime/src/lib.rs
Labels: documentation

#779 fix: remove wrappers
  Cargo.lock
  Cargo.toml
  crates/client/rpc-core/Cargo.toml
  crates/client/rpc-core/src/utils.rs
  crates/client/storage/Cargo.toml
  crates/client/storage/src/overrides/mod.rs
  crates/client/storage/src/overrides/schema_v1_override.rs
  crates/node/src/chain_spec.rs
  crates/pallets/starknet/Cargo.toml
  crates/pallets/starknet/src/blockifier_state_adapter.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/runtime_api.rs
  crates/pallets/starknet/src/tests/declare_tx.rs
  crates/pallets/starknet/src/tests/erc20.rs
  crates/pallets/starknet/src/tests/l1_message.rs
  crates/pallets/starknet/src/tests/mock/default_mock.rs
  crates/pallets/starknet/src/tests/mock/state_root_mock.rs
  crates/pallets/starknet/src/tests/mod.rs
  crates/pallets/starknet/src/tests/utils.rs
  crates/primitives/starknet/src/execution/contract_class_wrapper.rs
  crates/primitives/starknet/src/execution/mod.rs
  crates/primitives/starknet/src/starknet_serde/mod.rs
  crates/primitives/starknet/src/tests/crypto.rs
  crates/primitives/starknet/src/tests/execution.rs
  crates/primitives/starknet/src/transaction/mod.rs
  crates/primitives/starknet/src/transaction/types.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/lib.rs
Labels: enhancement, feature, refacto

#714 changed getEvents rpc, added 2 integrational tests
  crates/client/rpc/src/events/mod.rs
  crates/client/rpc/src/events/tests.rs
  crates/client/rpc/src/lib.rs
  crates/client/rpc/src/types.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/tests/deploy_account_tx.rs
  crates/pallets/starknet/src/tests/erc20.rs
  crates/pallets/starknet/src/tests/invoke_tx.rs
  crates/primitives/starknet/src/starknet_serde/mod.rs
  crates/primitives/starknet/src/tests/crypto.rs
  crates/primitives/starknet/src/tests/transaction.rs
  crates/primitives/starknet/src/transaction/mod.rs
  crates/primitives/starknet/src/transaction/types.rs
  tests/tests/test-rpc/test-starknet-rpc.ts
Labels: enhancement, rpc
