Repository keep-starknet-strange/madara, pull requests merged in 2023-07, with the labels that each got.

#814 test: add full cairo 1 test flow
  cairo-contracts/build/cairo_1/erc20.casm.json
  cairo-contracts/build/cairo_1/erc20.sierra.json
  cairo-contracts/src/cairo_1/erc20/erc20.cairo
  crates/client/rpc/src/lib.rs
  tests/tests/constants.ts
  tests/tests/test-rpc/test-starknet-rpc.ts
Labels: enhancement, testing

#823 fix estimate fee
  crates/pallets/starknet/src/lib.rs
Labels: bug

#893 build: update deps to non bugged cairo-rs
  Cargo.lock
Labels: bug, dependencies, Fix
