Repository keep-starknet-strange/madara, pull requests merged in 2023-10, with the labels that each got.

#1165 refacto: improve node cli
  .github/workflows/madara-commands.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/node/Cargo.toml
  crates/node/src/chain_spec.rs
  crates/node/src/cli.rs
  crates/node/src/command.rs
  crates/node/src/commands/mod.rs
  crates/node/src/commands/run.rs
  crates/node/src/commands/setup.rs
  crates/node/src/configs.rs
  crates/node/src/constants.rs
  crates/node/src/main.rs
  crates/node/src/service.rs
  crates/pallets/starknet/Cargo.toml
  crates/pallets/starknet/src/genesis_loader.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/tests/mock/setup_mock.rs
  crates/pallets/starknet/src/utils.rs
  docs/getting-started.md
  docs/rpc-contribution.md
  docs/sharingan-starter-pack.md
Labels: enhancement, refacto, ux

#1200 fix linter
  .all-contributorsrc
  README.md
Labels: Skip-Changelog

#1218 fix: clippy
  crates/primitives/fee/src/lib.rs
Labels: Skip-Changelog

#1217 Build CommitmentStateDiff based on new block storage changes
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/client/commitment-state-diff/Cargo.toml
  crates/client/commitment-state-diff/src/lib.rs
  crates/client/data-availability/Cargo.toml
  crates/client/data-availability/src/lib.rs
  crates/client/data-availability/src/utils.rs
  crates/node/Cargo.toml
  crates/node/src/service.rs
  crates/pallets/starknet/Cargo.toml
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/runtime_api.rs
  crates/primitives/felt/src/starkware_types_conversions.rs
  crates/primitives/storage/Cargo.toml
  crates/primitives/storage/src/lib.rs
  crates/runtime/src/lib.rs
Labels: feature

#1227 chore: fix typos
  crates/client/data-availability/src/lib.rs
  crates/client/transaction-pool/README.md
Labels: Skip-Changelog

#1215 Alter transaction checks for starknet-rs/foundry compatibility
  CHANGELOG.md
  crates/client/rpc/src/lib.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/runtime_api.rs
  crates/pallets/starknet/src/tests/query_tx.rs
  crates/runtime/src/lib.rs
Labels: Fix
