Repository keep-starknet-strange/madara, pull requests merged in 2023-05, with the labels that each got.

#349 Added hurl example files + updated documentation
  docs/getting-started.md
  docs/images/hurl-test-output.png
  docs/rpc-contribution.md
  examples/rpc/starknet/starknet_blockHashAndNumber.hurl
  examples/rpc/starknet/starknet_blockNumber.hurl
  examples/rpc/starknet/starknet_call.hurl
  examples/rpc/starknet/starknet_chainId.hurl
  examples/rpc/starknet/starknet_getBlockTransactionCount.hurl
  examples/rpc/starknet/starknet_getBlockWithTxHashes.hurl
  examples/rpc/starknet/starknet_getBlockWithTxs.hurl
  examples/rpc/starknet/starknet_getClass.hurl
  examples/rpc/starknet/starknet_getClassAt.hurl
  examples/rpc/starknet/starknet_getClassHashAt.hurl
  examples/rpc/starknet/starknet_getEstimateFee.hurl
  examples/rpc/starknet/starknet_getEvents.hurl
  examples/rpc/starknet/starknet_getNonce.hurl
  examples/rpc/starknet/starknet_getStateUpdate.hurl
  examples/rpc/starknet/starknet_getStorageAt.hurl
  examples/rpc/starknet/starknet_getTransactionByBlockIdAndIndex.hurl
  examples/rpc/starknet/starknet_getTransactionByHash.hurl
  examples/rpc/starknet/starknet_getTransactionReceipt.hurl
  examples/rpc/starknet/starknet_pendingTransactions.hurl
  examples/rpc/starknet/starknet_syncing.hurl
Labels: documentation

#211 Tests: Crate/Primitives tests
  crates/primitives/starknet/src/tests/block.rs
  crates/primitives/starknet/src/tests/crypto.rs
  crates/primitives/starknet/src/tests/state.rs
Labels: testing

#362 Refacto transaction types
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/tests/call_contract.rs
  crates/pallets/starknet/src/tests/declare_tx.rs
  crates/pallets/starknet/src/tests/deploy_account_tx.rs
  crates/pallets/starknet/src/tests/erc20.rs
  crates/pallets/starknet/src/tests/invoke_tx.rs
  crates/pallets/starknet/src/tests/l1_message.rs
  crates/primitives/starknet/src/block/serialize.rs
  crates/primitives/starknet/src/crypto/commitment/mod.rs
  crates/primitives/starknet/src/tests/crypto.rs
  crates/primitives/starknet/src/traits/hash.rs
  crates/primitives/starknet/src/transaction/mod.rs
  crates/primitives/starknet/src/transaction/types.rs
  tests/util/starknet.ts
Labels: enhancement, refacto

#365 fix: fix deploy test
  tests/tests/test-starknet/test-starknet-extrinsics.ts
  tests/util/starknet.ts
Labels: testing, Fix

#400 feat: header block hash ✨
  Cargo.lock
  crates/client/mapping-sync/src/sync_blocks.rs
  crates/client/rpc/src/lib.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/tests/current_block.rs
  crates/pallets/starknet/src/tests/invoke_tx.rs
  crates/primitives/starknet/src/block/header.rs
  crates/primitives/starknet/src/crypto/hash/pedersen.rs
  crates/primitives/starknet/src/traits/hash.rs
  tests/tests/test-rpc/test-starknet-rpc.ts
  tests/util/utils.ts
Labels: feature

#418 feat: refractoooor runtime types 🔥
  crates/client/rpc-core/src/utils.rs
  crates/client/rpc/src/lib.rs
  crates/client/storage/src/overrides/schema_v1_override.rs
  crates/node/src/chain_spec.rs
  crates/pallets/starknet/src/blockifier_state_adapter.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/message.rs
  crates/pallets/starknet/src/runtime_api.rs
  crates/pallets/starknet/src/state_root.rs
  crates/pallets/starknet/src/tests/account_helper.rs
  crates/pallets/starknet/src/tests/call_contract.rs
  crates/pallets/starknet/src/tests/current_block.rs
  crates/pallets/starknet/src/tests/declare_tx.rs
  crates/pallets/starknet/src/tests/deploy_account_tx.rs
  crates/pallets/starknet/src/tests/erc20.rs
  crates/pallets/starknet/src/tests/invoke_tx.rs
  crates/pallets/starknet/src/tests/l1_message.rs
  crates/pallets/starknet/src/tests/mock.rs
  crates/pallets/starknet/src/tests/utils.rs
  crates/pallets/starknet/src/types.rs
  crates/primitives/starknet/src/block/header.rs
  crates/primitives/starknet/src/block/mod.rs
  crates/primitives/starknet/src/block/serialize.rs
  crates/primitives/starknet/src/crypto/commitment/mod.rs
  crates/primitives/starknet/src/execution/call_entrypoint_wrapper.rs
  crates/primitives/starknet/src/execution/mod.rs
  crates/primitives/starknet/src/execution/program_wrapper.rs
  crates/primitives/starknet/src/starknet_serde/mod.rs
  crates/primitives/starknet/src/tests/crypto.rs
  crates/primitives/starknet/src/tests/execution.rs
  crates/primitives/starknet/src/tests/transaction.rs
  crates/primitives/starknet/src/transaction/mod.rs
  crates/primitives/starknet/src/transaction/types.rs
  crates/runtime/src/lib.rs
  docs/rpc-contribution.md
Labels: feature

#422 feat: Felt252Wrapper with SCALE encoding support
  .github/workflows/test.yml
  crates/client/mapping-sync/src/sync_blocks.rs
  crates/client/rpc-core/src/utils.rs
  crates/client/rpc/src/lib.rs
  crates/node/src/chain_spec.rs
  crates/pallets/starknet/src/blockifier_state_adapter.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/message.rs
  crates/pallets/starknet/src/tests/account_helper.rs
  crates/pallets/starknet/src/tests/call_contract.rs
  crates/pallets/starknet/src/tests/current_block.rs
  crates/pallets/starknet/src/tests/declare_tx.rs
  crates/pallets/starknet/src/tests/deploy_account_tx.rs
  crates/pallets/starknet/src/tests/erc20.rs
  crates/pallets/starknet/src/tests/invoke_tx.rs
  crates/pallets/starknet/src/tests/l1_message.rs
  crates/pallets/starknet/src/tests/mock.rs
  crates/pallets/starknet/src/tests/utils.rs
  crates/primitives/starknet/src/block/header.rs
  crates/primitives/starknet/src/block/mod.rs
  crates/primitives/starknet/src/block/serialize.rs
  crates/primitives/starknet/src/crypto/commitment/mod.rs
  crates/primitives/starknet/src/crypto/hash/mod.rs
  crates/primitives/starknet/src/crypto/hash/pedersen.rs
  crates/primitives/starknet/src/crypto/hash/poseidon.rs
  crates/primitives/starknet/src/execution/call_entrypoint_wrapper.rs
  crates/primitives/starknet/src/execution/felt252_wrapper.rs
  crates/primitives/starknet/src/execution/mod.rs
  crates/primitives/starknet/src/execution/program_wrapper.rs
  crates/primitives/starknet/src/starknet_serde/mod.rs
  crates/primitives/starknet/src/tests/crypto.rs
  crates/primitives/starknet/src/tests/execution.rs
  crates/primitives/starknet/src/tests/starknet_serde.rs
  crates/primitives/starknet/src/tests/transaction.rs
  crates/primitives/starknet/src/traits/hash.rs
  crates/primitives/starknet/src/transaction/mod.rs
  crates/primitives/starknet/src/transaction/types.rs
  examples/rpc/starknet/starknet_addInvokeTransaction.hurl
  tests/tests/test-rpc/test-starknet-rpc.ts
  tests/tests/test-starknet/test-starknet-extrinsics.ts
  tests/util/setup-dev-tests.ts
  tests/util/utils.ts
Labels: feature, refacto

#462 Clean npm dependencies 🧹
  benchmarking/package-lock.json
  tests/package-lock.json
  tests/package.json
  tests/tests/test-starknet/test-starknet-extrinsics.ts
  tests/util/setup-dev-tests.ts
Labels: testing, Fix

#451 dev: remove ci warnings
  .github/workflows/docker.yml
Labels: infra, devops

#461 check for regression in the ci
  .codecov.yml
  .github/workflows/benchmark.yml
  scripts/check-regression.py
  scripts/check-regression.sh
Labels: devops

#448 feat: get runtime hasher into client
  crates/client/mapping-sync/src/lib.rs
  crates/client/mapping-sync/src/sync_blocks.rs
  crates/client/rpc/src/lib.rs
  crates/node/src/rpc/mod.rs
  crates/node/src/service.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/runtime_api.rs
  crates/pallets/starknet/src/tests/invoke_tx.rs
  crates/primitives/starknet/src/block/header.rs
  crates/primitives/starknet/src/crypto/commitment/mod.rs
  crates/primitives/starknet/src/crypto/hash/mod.rs
  crates/primitives/starknet/src/crypto/hash/pedersen.rs
  crates/primitives/starknet/src/crypto/hash/poseidon.rs
  crates/primitives/starknet/src/crypto/merkle_patricia_tree/merkle_node.rs
  crates/primitives/starknet/src/crypto/merkle_patricia_tree/merkle_tree.rs
  crates/primitives/starknet/src/tests/crypto.rs
  crates/primitives/starknet/src/traits/hash.rs
  crates/primitives/starknet/src/traits/mod.rs
  crates/runtime/src/lib.rs
Labels: enhancement

#470 fix: clean the macros and unused code
  crates/primitives/starknet/src/execution/felt252_wrapper.rs
Labels: refacto

#476 feat: addDeclareTransaction ✨
  Cargo.lock
  crates/client/rpc-core/Cargo.toml
  crates/client/rpc-core/src/utils.rs
  crates/client/rpc/src/lib.rs
  crates/primitives/starknet/src/execution/entrypoint_wrapper.rs
  tests/contracts/compiled/erc20.json
  tests/tests/constants.ts
  tests/tests/test-rpc/test-starknet-rpc.ts
Labels: rpc, feature
