Repository keep-starknet-strange/madara, pull requests merged in 2023-11, with the labels that each got.

#1255 🐛 fix rpc test
  starknet-rpc-test/call.rs
Labels: Skip-Changelog

#1253 Fix: aarch64 linux bin
  .github/workflows/binaries-build.yml
Labels: Skip-Changelog

#1267 fix(starknet_rpc/get_transaction_receipt): async loop to get pending tx
  CHANGELOG.md
  Cargo.lock
  crates/client/rpc-core/src/lib.rs
  crates/client/rpc/Cargo.toml
  crates/client/rpc/src/lib.rs
Labels: Fix

#1216 dev: return deployed contract address in `get_transaction_receipt` api
  CHANGELOG.md
  crates/client/rpc/src/lib.rs
  crates/pallets/starknet/src/lib.rs
  crates/pallets/starknet/src/runtime_api.rs
  crates/pallets/starknet/src/tests/deploy_account_tx.rs
  crates/pallets/starknet/src/tests/erc20.rs
  crates/pallets/starknet/src/tests/invoke_tx.rs
  crates/primitives/fee/src/lib.rs
  crates/runtime/src/lib.rs
  starknet-rpc-test/get_transaction_receipt.rs
Labels: feature

#1268 chore: remove duplicated repo from polkadot-sdk
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/client/block-proposer/Cargo.toml
  crates/client/block-proposer/src/lib.rs
  crates/client/rpc/Cargo.toml
  crates/client/rpc/src/events/mod.rs
  crates/client/rpc/src/lib.rs
  crates/client/transaction-pool/Cargo.toml
  crates/client/transaction-pool/README.md
  crates/client/transaction-pool/src/api.rs
  crates/client/transaction-pool/src/enactment_state.rs
  crates/client/transaction-pool/src/error.rs
  crates/client/transaction-pool/src/graph/base_pool.rs
  crates/client/transaction-pool/src/graph/future.rs
  crates/client/transaction-pool/src/graph/listener.rs
  crates/client/transaction-pool/src/graph/mod.rs
  crates/client/transaction-pool/src/graph/pool.rs
  crates/client/transaction-pool/src/graph/ready.rs
  crates/client/transaction-pool/src/graph/rotator.rs
  crates/client/transaction-pool/src/graph/tracked_map.rs
  crates/client/transaction-pool/src/graph/validated_pool.rs
  crates/client/transaction-pool/src/graph/watcher.rs
  crates/client/transaction-pool/src/lib.rs
  crates/client/transaction-pool/src/metrics.rs
  crates/client/transaction-pool/src/revalidation.rs
  crates/client/transaction-pool/src/tests.rs
  crates/client/transaction-pool/tests/pool.rs
  crates/node/Cargo.toml
  crates/node/src/rpc/mod.rs
  crates/node/src/service.rs
Labels: devx:build

#1273 chore: run cargo update
  Cargo.lock
Labels: Skip-Changelog
